language: php
php:
- 7.0
before_script: composer install -n
script: phpunit -c app
before_install:
- openssl aes-256-cbc -K $encrypted_928069d7bbc2_key -iv $encrypted_928069d7bbc2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
