language: php
php:
- 7.0
before_script: composer install -n
script: phpunit -c app
addons:
  ssh_known_hosts: jyps.fi
before_deploy:
- openssl aes-256-cbc -K $encrypted_928069d7bbc2_key -iv $encrypted_928069d7bbc2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ git@jyps.fi:/tmp/deplotesti
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_928069d7bbc2_key -iv $encrypted_928069d7bbc2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
