jyps_register:
    resource: "@JYPSRegisterBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /member/login
    defaults:  { _controller: JYPSRegisterBundle:Security:login }

login_check:
    path:   /member/login_check
  
logout:
    path:   /member/logout

member:
    pattern: /member/show/{memberid}
    defaults: { _controller: JYPSRegisterBundle:Member:showAll }
    requirements:
        id:  \d+

all_members:
    path:   /member
    defaults:  { _controller: JYPSRegisterBundle:Member:index }

add_member:
    path:   /member/add
    defaults:  { _controller: JYPSRegisterBundle:Member:addMember }

search:
    path:   /member/search
    defaults:  { _controller: JYPSRegisterBundle:Member:searchMembers }

searchOld:
    path:   /member/searchOld
    defaults:  { _controller: JYPSRegisterBundle:Member:searchOldMembers }

join_member:
    path: /join
    defaults:  { _controller: JYPSRegisterBundle:Member:joinMember}
    methods:  [GET]

join_save:
    path: /join/joinSave
    defaults:  { _controller: JYPSRegisterBundle:Member:joinSave}
    methods:  [POST]

join_internal_save:
    path: /member/joinSave
    defaults:  { _controller: JYPSRegisterBundle:Member:joinSaveInternal}

join_complete:
    path: /join/joinComplete
    defaults: {_controller: JYPSRegisterBundle:Member:joinComplete}
    methods:  [GET]

configuration:
    path: /member/configuration
    defaults: {_controller: JYPSRegisterBundle:Configuration:showAll}

memberfees:
    path: /member/memberfees
    defaults: {_controller: JYPSRegisterBundle:MemberFee:showAll}

memberfees_create:
    path: /member/memberfees/create
    defaults: {_controller: JYPSRegisterBundle:MemberFee:createMemberFees}

end_member:
    path:   /member/end_member
    defaults:  { _controller: JYPSRegisterBundle:Member:endMember}

mark_member_fees:
    path:   /member/memberfees/showFees
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:showUnpaidFees}

mark_fees:
    path:   /member/memberfees/markUnpaidFees
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:markFeesPaid}

showClosed:
    path:   /member/history
    defaults:  { _controller: JYPSRegisterBundle:Member:showClosed}

restoreMember:
    path:   /member/history/restore
    defaults:  { _controller: JYPSRegisterBundle:Member:restoreMember}

JYPSRegisterBundle_user:
    resource: "@JYPSRegisterBundle/Resources/config/routing/user.php"
    prefix:   /member/user

JYPSRegisterBundle_member_intrestconfig:
    resource: "@JYPSRegisterBundle/Resources/config/routing/intrestconfig.php"
    prefix:   /member/intrestconfig

index_password:
    path:   /member/changePassword
    defaults:  { _controller: JYPSRegisterBundle:PasswordChange:index}

member_statistics:
    path:   /member/statistics
    defaults:  { _controller: JYPSRegisterBundle:Member:memberStatistics}

showQuickReports:
    path:   /member/reports
    defaults:  { _controller: JYPSRegisterBundle:Report:index}

sendReminders:
    path:   /member/memberfees/sendReminders
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:sendReminderLetter}

exportAddressExcel:
    path:   /member/addressExcel
    defaults:  { _controller: JYPSRegisterBundle:Member:addressExcel}

memberActions:
    path:   /member/memberactions
    defaults:  { _controller: JYPSRegisterBundle:Member:memberExtra}

magazineInfo:
    path:   /member/magazineInfo
    defaults:  { _controller: JYPSRegisterBundle:Member:sendMagazineLink}

communicationMail:
    path:   /member/communicationMail
    defaults:  { _controller: JYPSRegisterBundle:Member:sendCommunicationMail}

sendCard:
    path:   /member/send_membership_card
    defaults:  { _controller: JYPSRegisterBundle:Member:sendMembershipCard}

addChildMember:
    path: /member/addChildMember
    defaults: {_controller: JYPSRegisterBundle:Member:addChildMember}

removeChildMember:
    path: /member/removeChildMember
    defaults: {_controller: JYPSRegisterBundle:Member:removeChildMember }

sendMemberFeeEmail:
    path: /member/memberfees/sendEmail
    defaults: {_controller: JYPSRegisterBundle:MemberFee:sendMemberFeeEmails }

sendSingleMemberFeeEmail:
    path: /member/memberfees/sendSingleEmail
    defaults: {_controller: JYPSRegisterBundle:MemberFee:sendOneMemberFeeEmail }

acme_blog:
    type: rest
    prefix: /member/api
    resource: "@JYPSRegisterBundle/Resources/config/routes.yml"  
