parameters:
#    jyps_register.example.class: JYPS\RegisterBundle\Example

services:
#    jyps_register.example:
#        class: %jyps_register.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
